[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
guess_game = "5aEZQf3hvt1bEyKEYnvy1zTNjwR5qwAagc7Aqdm43qfM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\shive\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
